#!/usr/bin/env node
/**
 * Dump viem `as const` ABIs from `forge inspect`.
 *
 *   node packages/onchain-setup/scripts/generate-abi.mjs
 *
 * Re-run whenever a contract's ABI changes. `src/abi.test.ts` fails if the
 * committed files drift from Foundry's output.
 */
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const forgeRoot = join(packageRoot, "evm");
const outDir = join(packageRoot, "src/generated");
mkdirSync(outDir, { recursive: true });

const contracts = [
  ["AvtarEscrow", "escrowAbi"],
  ["AvtarAgentRegistry", "registryAbi"],
  ["Groth16Verifier", "verifierAbi"],
];

for (const [contract, exportName] of contracts) {
  const raw = execSync(`forge inspect ${contract} abi --json`, {
    cwd: forgeRoot,
    encoding: "utf8",
  });
  const abi = JSON.parse(raw);
  const body = `// Generated by scripts/generate-abi.mjs — do not edit.
// Source: \`forge inspect ${contract} abi\`

export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;
`;
  writeFileSync(join(outDir, `${exportName}.ts`), body);
  console.log(`wrote src/generated/${exportName}.ts (${abi.length} items)`);
}
